spring:
  application:
    name: credit-client
  datasource:
    url: jdbc:postgresql://localhost:5432/onlinebankm
    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0

logging:
  level:
    sql: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}