spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka


