spring:
  application:
    name: eureka-server

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka